### ISSUE TITLE
Led not setting pinmode?

### ISSUE THREAD

**Issue by makenai** [bryan-m-hughes/raspi-io#10]
Running with the johnny-five example, I'm getting this error:
```
Error: Cannot digitalWrite to pin "7" unless it is in OUTPUT mode
    at Raspi.Object.defineProperty.value [as digitalWrite] (/home/pi/spaceJS/node_modules/raspi-io/lib/index.js:307:13)
    at Led.Controllers.DEFAULT.write.value (/home/pi/spaceJS/node_modules/johnny-five/lib/led.js:125:19)
    at Led.on (/home/pi/spaceJS/node_modules/johnny-five/lib/led.js:257:8)
    at Led.toggle (/home/pi/spaceJS/node_modules/johnny-five/lib/led.js:281:40)
    at Led.<anonymous> (/home/pi/spaceJS/node_modules/johnny-five/lib/led.js:462:10)
    at wrapper [as _onTimeout] (timers.js:261:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

Code:

```
var raspi = require('raspi-io');
var five = require('johnny-five');
var board = new five.Board({
  io: new raspi()
});

board.on('ready', function() {

  // Create an Led on pin 7 (GPIO4) and strobe it on/off
  // Optionally set the speed; defaults to 100ms
  (new five.Led('P1-7')).strobe();

});
```

**Comment by bryan-m-hughes** [comment]
Fixed with 2.0.4 of raspi-io and 0.8.41 of johnny-five, both rolled out just now.
