### ISSUE TITLE
Pins aren’t being aliased

### ISSUE THREAD

**Issue by bmordan** [bryan-m-hughes/raspi-io#13]
This raises an error
```
this.pinMode('GPIO17', five.Pin.OUTPUT)
```
/home/pi/node_modules/raspi-io/lib/index.js:231
      throw new Error('Unknown pin "' + pin + '"');
            ^
Error: Unknown pin "GPIO17"
    at Raspi.Object.defineProperty.value [as __$271828_5$__] (/home/pi/node_modules/raspi-io/lib/index.js:231:13)
    at Raspi.Object.defineProperty.value [as pinMode] (/home/pi/node_modules/raspi-io/lib/index.js:240:43)
    at Board.(anonymous function) [as pinMode] (/home/pi/node_modules/johnny-five/lib/board.js:445:20)
    at Board.<anonymous> (/home/pi/init.js:8:8)
    at Board.emit (events.js:95:17)
    at Board.broadcast (/home/pi/node_modules/johnny-five/lib/board.js:427:8)
    at Board.<anonymous> (/home/pi/node_modules/johnny-five/lib/board.js:329:21)
    at Raspi.g (events.js:180:16)
    at Raspi.emit (events.js:92:17)
    at /home/pi/node_modules/raspi-io/lib/index.js:205:10
```
this.pinMode(0, five.Pin.OUTPUT)
```
The numerical reference is OK and works

**Comment by bryan-m-hughes** [comment]
Fixed with version 2.0.7 of raspi-io
