### ISSUE TITLE
npm install raspi-io not working anymore

### ISSUE THREAD

**Issue by valentinvieriu** [bryan-m-hughes/raspi-io#4]
Here is the output of the command. I 'm using a Raspberry Model B
```

root@raspberrypi:~# npm install --save raspi-io
-
> raspi-wiringpi@1.0.2 install /root/node_modules/raspi-io/node_modules/raspi-core/node_modules/raspi-wiringpi
> sh install-wiringpi.sh

Installing I2C tools
Reading package lists... Done
Building dependency tree
Reading state information... Done
libi2c-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

Downloading Wiring Pi...

install-wiringpi.sh: 35: install-wiringpi.sh: git: not found
install-wiringpi.sh: 36: cd: can't cd to wiringPi

Building Wiring Pi. You may be asked for your root password.

sudo: ./build: command not found

> raspi-pwm@1.0.1 install /root/node_modules/raspi-io/node_modules/raspi-pwm
> node-gyp rebuild

make: Entering directory '/root/node_modules/raspi-io/node_modules/raspi-pwm/build'
  CXX(target) Release/obj.target/addon/src/addon.o
  CXX(target) Release/obj.target/addon/src/init.o
../src/init.cc:27:22: fatal error: wiringPi.h: No such file or directory
compilation terminated.
addon.target.mk:84: recipe for target 'Release/obj.target/addon/src/init.o' failed
make: *** [Release/obj.target/addon/src/init.o] Error 1
make: Leaving directory '/root/node_modules/raspi-io/node_modules/raspi-pwm/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.12.28+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/node_modules/raspi-io/node_modules/raspi-pwm
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

> raspi-gpio@1.0.2 install /root/node_modules/raspi-io/node_modules/raspi-gpio
> node-gyp rebuild

make: Entering directory '/root/node_modules/raspi-io/node_modules/raspi-gpio/build'
  CXX(target) Release/obj.target/addon/src/addon.o
  CXX(target) Release/obj.target/addon/src/init.o
../src/init.cc:27:22: fatal error: wiringPi.h: No such file or directory
compilation terminated.
addon.target.mk:85: recipe for target 'Release/obj.target/addon/src/init.o' failed
make: *** [Release/obj.target/addon/src/init.o] Error 1
make: Leaving directory '/root/node_modules/raspi-io/node_modules/raspi-gpio/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.12.28+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/node_modules/raspi-io/node_modules/raspi-gpio
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

> raspi-core@1.1.2 install /root/node_modules/raspi-io/node_modules/raspi-core
> node-gyp rebuild

make: Entering directory '/root/node_modules/raspi-io/node_modules/raspi-core/build'
  CXX(target) Release/obj.target/addon/src/addon.o
  CXX(target) Release/obj.target/addon/src/init.o
../src/init.cc:25:22: fatal error: wiringPi.h: No such file or directory
compilation terminated.
addon.target.mk:83: recipe for target 'Release/obj.target/addon/src/init.o' failed
make: *** [Release/obj.target/addon/src/init.o] Error 1
make: Leaving directory '/root/node_modules/raspi-io/node_modules/raspi-core/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.12.28+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/node_modules/raspi-io/node_modules/raspi-core
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! raspi-pwm@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raspi-pwm@1.0.1 install script.
npm ERR! This is most likely a problem with the raspi-pwm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls raspi-pwm
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.12.28+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "raspi-io"
npm ERR! cwd /root
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

```

**Comment by matthewd92** [comment]
I am having similar issues with installing raspi-io.  The error that I am getting is that it can not find compatible versions of certain components such as raspi-pwm or raspi-board.  I followed the instructions above for getting wiringpin and that error went away.  Any ideas?  This is for as B+ that I just received

**Comment by bryan-m-hughes** [comment]
Can you paste the exact error message you're getting?

**Comment by matthewd92** [comment]
root@raspberrypi:/home/pi# npm install raspi-io
npm http GET http://registry.npmjs.org/raspi-io
npm http 304 http://registry.npmjs.org/raspi-io
npm http GET http://registry.npmjs.org/raspi-board
npm http GET http://registry.npmjs.org/raspi-core
npm http GET http://registry.npmjs.org/raspi-gpio
npm http GET http://registry.npmjs.org/raspi-pwm
npm http 304 http://registry.npmjs.org/raspi-gpio
npm http 304 http://registry.npmjs.org/raspi-board
npm http 304 http://registry.npmjs.org/raspi-pwm
npm http 304 http://registry.npmjs.org/raspi-core
npm ERR! Error: No compatible version found: raspi-gpio@'^1.0.3'
npm ERR! Valid install targets:
npm ERR! ["1.0.0","1.0.1","1.0.2","1.0.3","1.0.4"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:682:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:597:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:93:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.12.22+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "raspi-io"
npm ERR! cwd /home/pi
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.14
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0

**Comment by bryan-m-hughes** [comment]
that...makes no sense. It says it needs 1.0.3 or newer, but as you can see in the targets list that 1.0.3 and 1.0.4 are there.

Have you tried deleting your entire ```node_modules``` folder and reinstalling from scratch?

Also, which version of node.js and npm are you using?

**Comment by matthewd92** [comment]
pi@raspberrypi ~ $ nodejs -v
v0.6.19
pi@raspberrypi ~ $ npm -v
1.2.14

I deleted and reinstalled last night. I just set it up last night as we just got it

**Comment by bryan-m-hughes** [comment]
Ah, I see why now. raspi-io and johnny-five are only supported on node 0.8 or newer (and 0.10 or newer in practice).

Try installing it from http://node-arm.herokuapp.com/

**Comment by matthewd92** [comment]
Thank you @bryan-m-hughes for the quick response.  I will try that this evening.
