### ISSUE TITLE
Accessing pins by physical location on raspberry pi doesn't seem to work

### ISSUE THREAD

**Issue by motiooon** [bryan-m-hughes/raspi-io#9]
Gist with the code:
https://gist.github.com/motiooon/eb5be4823d3e3a133c50

Error stack:

/home/pi/projects/johnny-five/node_modules/raspi-io/lib/index.js:231
      throw new Error('Unknown pin "' + pin + '"');
            ^
Error: Unknown pin "P1-16"
    at Raspi.Object.defineProperty.value [as __$271828_5$__] (/home/pi/projects/johnny-five/node_modules/raspi-io/lib/index.js:231:13)
    at Raspi.Object.defineProperty.value [as pinMode] (/home/pi/projects/johnny-five/node_modules/raspi-io/lib/index.js:240:43)
    at Raspi.<anonymous> (/home/pi/projects/johnny-five/start.js:16:9)
    at Raspi.emit (events.js:92:17)
    at /home/pi/projects/johnny-five/node_modules/raspi-io/lib/index.js:204:10

**Comment by bryan-m-hughes** [comment]
As we discussed in gitter, this is actually the expected behavior, and using Johnny-Five instead of raspi-io directly will get you the pin mapping you want.
